public class Test extends java.lang.Object
{
    private static int parametar;

    public void <init>()
    {
        word r0;

        r0 := @this: Test;

        load.r r0;

        specialinvoke <java.lang.Object: void <init>()>;

        return;
    }

    public static void makeSwitch()
    {
        staticget <Test: int parametar>;

        lookupswitch
        {
            case 1: goto label1;
            case 2: goto label2;
            default: goto label3;
        };

     label1:
        staticget <java.lang.System: java.io.PrintStream out>;

        push "1";

        virtualinvoke <java.io.PrintStream: void println(java.lang.String)>;

        goto label4;

     label2:
        staticget <java.lang.System: java.io.PrintStream out>;

        push "2";

        virtualinvoke <java.io.PrintStream: void println(java.lang.String)>;

        goto label4;

     label3:
        staticget <java.lang.System: java.io.PrintStream out>;

        push "default";

        virtualinvoke <java.io.PrintStream: void println(java.lang.String)>;

     label4:
        push 1;

        tableswitch
        {
            case 1: goto label5;
            case 2: goto label6;
            case 3: goto label7;
            default: goto label8;
        };

     label5:
        goto label8;

     label6:
        goto label8;

     label7:
        goto label8;

     label8:
        return;
    }

    public static void sayHello()
    {
        staticget <java.lang.System: java.io.PrintStream out>;

        push "Hello.";

        virtualinvoke <java.io.PrintStream: void println(java.lang.String)>;

        return;
    }

    public static void main(java.lang.String[])
    {
        word r0;

        r0 := @parameter0: java.lang.String[];

        staticget <java.lang.System: java.io.PrintStream out>;

        new java.lang.StringBuilder;

        dup1.r;

        specialinvoke <java.lang.StringBuilder: void <init>()>;

        push "";

        virtualinvoke <java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>;

        push 1;

        virtualinvoke <java.lang.StringBuilder: java.lang.StringBuilder append(int)>;

        virtualinvoke <java.lang.StringBuilder: java.lang.String toString()>;

        virtualinvoke <java.io.PrintStream: void println(java.lang.String)>;

        goto label1;

     label1:
        push 0;

        store.i r0;

     label2:
        load.i r0;

        push 10;

        ifcmpge.i label3;

        staticget <java.lang.System: java.io.PrintStream out>;

        new java.lang.StringBuilder;

        dup1.r;

        specialinvoke <java.lang.StringBuilder: void <init>()>;

        push "..";

        virtualinvoke <java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>;

        load.i r0;

        virtualinvoke <java.lang.StringBuilder: java.lang.StringBuilder append(int)>;

        virtualinvoke <java.lang.StringBuilder: java.lang.String toString()>;

        virtualinvoke <java.io.PrintStream: void println(java.lang.String)>;

        inc.i r0 1;

        goto label2;

     label3:
        staticinvoke <Test: void sayHello()>;

        return;
    }
}
